stages:
  - test
  - sonar
  - smoke
  - dependencies

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  key: "$CI_JOB_NAME"  
  paths:
    - .m2/repository

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 
test:
  stage: test
  script: mvn $MAVEN_CLI_OPTS clean verify

sonar:
  stage: sonar
  script: 
  - mvn $MAVEN_CLI_OPTS clean verify sonar:sonar --settings settings.xml

smoke:
  stage: smoke
  script: mvn $MAVEN_CLI_OPTS clean verify
  artifacts:
    paths:
      - target/load.jar
    expire_in: 10m
  script:
  - scp -P $LOADER_PORT target/load.jar $LOADER_URL
  - ssh git@zeus.svenkubiak.de -p $LOADER_PORT 'sudo /opt/scripts/loader.sh'
  only:
  - master

dependencies:
  stage: dependencies
  script: mvn $MAVEN_CLI_OPTS clean verify versions:dependency-updates-report
  artifacts:
    paths:
      - target/site/dependency-updates-report.html
    expire_in: 10m
  script:
  - scp -P $LOADER_PORT target/site/dependency-updates-report.html $LOADER_URL
  - ssh git@zeus.svenkubiak.de -p $LOADER_PORT 'sudo /opt/scripts/dependencies.sh'
  only:
    - /^feature.*$/