language: java
jdk:
  - openjdk11
script: "mvn clean test -Dgpg.skip=true"
notifications:
  email: sk@svenkubiak.de

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
