default:
    application:
        name       : TEST 
        secret     : myvoiceismypassword
        language   : en
        host       : localhost
        port       : 9898
        minify:
            js        : true
            css       : true
            jsfolder  : /foo
            cssfolder : /bar
            gzipjs    : false
            gzipcss   : false
    auth:
        redirect  : /login
        cookie:
            name    : TEST-AUTH
            encrypt : false
            expires : 3600
    oauth:
        twitter:
            key       : kcfkZ30touFa1bQ812WaLhsnz
            secret    : ov01NMFidE7sYWHlC4oaTKJ9R4bgntJB6JrSsYbV4d8x2IO9N5
            callback  : http://localhost:50000/authenticate?oauth=twitter           
    cookie:
        name       : TEST-SESSION
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   : foo
        password   : bar
        ssl        : false
        
test:
    application:
        port           : 10808
        admin:
              health   : true
              config   : true
              cache    : true
              routes   : true
    smtp:
        port       : 3055

dev:
    application:
        port       : 50000
        admin:
                  health   : true
                  config   : true
                  cache    : true
                  routes   : true
                  metrics  : true        
    smtp:
        port       : 3125