# Application configuration
#
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name       : TEST
        secret     : Jb3MenqcohfVQNi3mYBBoYGk8JQ94u5cvEWz9rZMR1EED9t3l8eWwuF1jyXLDzvvZpMznuWeOlnfcNss0qlimeK8MA5McCCPeo2fhC
        language   : en
        timer      : true
        minify:
            js        : true
            css       : true
        preprocess:
            js        : true
            css       : true
    connector:
        http:
            host      : localhost
            port      : 9898
        ajp:
            host      : localhost
            port      : 9899
    session:
       cookie:
          name: test-session
          signkey: cPg4dO20cdvYw6sWn0g9L15RPYZpMznuWeOlnfcNss0qlimeK8MA5McCCPeo2fhC
    flash:
       cookie:
          name: test-flash
          signkey: 2GC5DKQCTd7ysQ8C6eSQbdtiNHvHu5cvEWz9rZMR1EED9t3l8eWwuF1jyXLDzvvd
    metrics:
       enable: true
    authentication:
        redirect  : /login
        cookie:
            name    : test-authentication
            encrypt : false
            expires : 3600
            signkey : 2GC5DKQCTd7ysQ8C6eSQbdtiNHvH6obfo1ISDxj3KpuH6BkpKOIIgUhR2UA7TgmK
    oauth:
        twitter:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=twitter
        google:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=google
        facebook:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=facebook
    smtp:
        host       : localhost
        port       : 25
        username   : foo
        password   : bar
        ssl        : false

test:
    application:
        masterkeyfile    : ./key/masterkey.txt
        foo              : cryptex[MloJcu6/zaaNs7gfpfZATg==]
        bar              : cryptex[NtUQaVGVUAVoTsl2c1HMDw==, 2]  
        foobar           : cryptex[WqfTFTyaEW2umq5d47Twow==, 3]               
        admin:
              enable     : true
              username   : cryptex[MloJcu6/zaaNs7gfpfZATg==]
              password   : $2a$12$eEIuI88oeA7zcqZgPBsM8OsqFCZuoyxzqgWVJDUDddUUIfvR.I7Uy
    connector:
        http:
            host      : localhost
            port      : 10808
        ajp:
            host      : localhost
            port      : 10809
    smtp:
        port       : 3055
        username   :

dev:
    application:
        masterkeyfile    : ./key/masterkey.txt
        admin:
              enable     : true
              username   : cryptex[MloJcu6/zaaNs7gfpfZATg==]
              password   : $2a$12$eEIuI88oeA7zcqZgPBsM8OsqFCZuoyxzqgWVJDUDddUUIfvR.I7Uy
    connector:
        http:
            host      : localhost
            port      : 50000
        ajp:
            host      : localhost
            port      : 50001
    smtp:
        port       : 3125
