# Application configuration
#
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name       : mangooio.examples
        secret     : myvoiceismypasswordmyvoiceismypassword
        language   : en
    connector:
        http:
            host      : localhost
            port      : 8080
    auth:
        redirect  : /login
        cookie:
            name    : EXAMPLE-AUTH
            encrypt : false
            expires : 3600
            secure  : false
    cookie:
        name       : TEST-SESSION
        expires    : 86400
        encryption : false

test:
    connector:
        http:
            host      : localhost
            port      : 10808

dev:
    connector:
        http:
            host      : localhost
            port      : 9000
