routes:
# Routes configuration
#
# This file defines all application routes.
# All routes start with an identifier of the method, followed by the
# url, followed by a mapping to the controller class and method. For
# some types a controller and method is not required.
#
# You can find a detailed explation of the routing file in the documentation
# https://mangoo.io/documentation#_routes
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ApplicationController
- method: GET
  url: /
  mapping: ApplicationController.index

# AuthenticationController
- method: GET
  url: /login
  mapping: AuthenticationController.login

- method: POST
  url: /authenticate
  mapping: AuthenticationController.authenticate

- method: POST
  url: /logout
  mapping: AuthenticationController.logout

# Resource path and resource files
- method: PATH
  url: /assets/

- method: FILE
  url: /robots.txt
