# Application configuration
#
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name          : ${application-name}
        secret        : application.secret
        language      : en
        admin:
            enable    : false
        minify:
            js        : false
            css       : false
    connector:
        http:
            host      : localhost
            port      : 8080
    metrics:
        enable        : false
    authentication:
        redirect      : /login
        cookie:
            name          : ${application-name}-authentication
            signkey       : authentication.cookie.signkey
            encryptionkey : authentication.cookie.encryptionkey
    session:
      cookie:
        name          : ${application-name}-session
        signkey       : session.cookie.signkey
        encryptionkey : session.cookie.encryptionkey
    flash:
      cookie:
        name          : ${application-name}-flash
        signkey       : flash.cookie.signkey  
        encryptionkey : flash.cookie.encryptionkey            
    smtp:
        host          : localhost
        port          : 25
        username      :
        password      :
        ssl           : false

test:
    connector:
        http:
            host      : localhost
            port      : 9090
    smtp:
        port          : 3025

dev:
    connector:
        http:
            host      : localhost
            port      : 9090
    smtp:
        port          : 3025